apiVersion: v1
kind: Pod
metadata:
  name: %podname%
  namespace: default
spec:
  containers:
  - name: %podname%
    image: togoetha/virtual-kubelet
    command: ["/usr/bin/virtual-kubelet"]
    args: ["--provider", "web", "--nodename", "vkubelettest", "--log-level", "debug"]
    env:
    - name: WEB_ENDPOINT_URL
      value: "%serviceUrl%"
    - name: KUBERNETES_SERVICE_HOST
      value: "%kubernetesHost%"
    - name: KUBERNETES_SERVICE_PORT
      value: "%kubernetesPort%"
    - name: KUBELET_PORT
      value: "%kubeletPort%"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kubeconfig
  volumes:
  - name: kubeconfig
    hostPath:
      path: /var/run/secrets/kubernetes.io/serviceaccount
      type: Directory
  nodeSelector:
    vpodmaster: "true"
